server:
  port: 8081
spring:
  application:
    name: Backend FMO
  jpa:
    database-platform: com.backendfmo.db.dialect.SQLiteDialect
    show-sql: true
  datasource:
    url: jdbc:sqlite:src/main/java/com/backendfmo/db/test.db
    driver-class-name: org.sqlite.JDBC
